import { Inter } from "next/font/google";
import Head from "next/head";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Trial Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToggleRender
        render={(name, state, toggle) => {
          return (
            <div>
              <h1>SHOW ME {name}</h1>
              <button onClick={toggle}>SHOW/HIDE {`${state}`}</button>
            </div>
          );
        }}
      />
    </>
  );
}

export const ToggleRender = (props) => {
  const { render } = props;
  const [state, setState] = useState(true);

  const toggle = () => {
    setState(!state);
  };

  return render("Hello Scott", state, toggle)
};
